// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYtKjMUHvYex6NMoWyNF9c1Uv4i5u2Gbo',
    appId: '1:509541637451:web:af72f0b281370593c11cce',
    messagingSenderId: '509541637451',
    projectId: 'eventlink-b7f75',
    authDomain: 'eventlink-b7f75.firebaseapp.com',
    storageBucket: 'eventlink-b7f75.firebasestorage.app',
    measurementId: 'G-DKB5HRRVPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYlbKc3NDAklZzaEejCf12RFWMU8ciFSY',
    appId: '1:509541637451:android:49c98d6153be9f86c11cce',
    messagingSenderId: '509541637451',
    projectId: 'eventlink-b7f75',
    storageBucket: 'eventlink-b7f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKfnaa8sSv4vZnprQ_zSCsaq3DfG0PvM',
    appId: '1:509541637451:ios:33240de2d7d5ffa1c11cce',
    messagingSenderId: '509541637451',
    projectId: 'eventlink-b7f75',
    storageBucket: 'eventlink-b7f75.firebasestorage.app',
    iosBundleId: 'com.example.eventlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBKfnaa8sSv4vZnprQ_zSCsaq3DfG0PvM',
    appId: '1:509541637451:ios:33240de2d7d5ffa1c11cce',
    messagingSenderId: '509541637451',
    projectId: 'eventlink-b7f75',
    storageBucket: 'eventlink-b7f75.firebasestorage.app',
    iosBundleId: 'com.example.eventlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYtKjMUHvYex6NMoWyNF9c1Uv4i5u2Gbo',
    appId: '1:509541637451:web:f05b4c4a1b0a138fc11cce',
    messagingSenderId: '509541637451',
    projectId: 'eventlink-b7f75',
    authDomain: 'eventlink-b7f75.firebaseapp.com',
    storageBucket: 'eventlink-b7f75.firebasestorage.app',
    measurementId: 'G-6BJ6NVJBVJ',
  );
}
